# **Reshape**

In [1]:
import numpy as np

array = np.arange(12)
print("Original array:")
print(array)

reshaped_array = array.reshape(3, 4)    # Reshaping array to 3x4
print("\nReshaped array (3x4):")
print(reshaped_array)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# **Concatenate**

In [2]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_array_0 = np.concatenate((array1, array2), axis=0)   # Concatenate along axis 0 (rows)
print("\nConcatenated array along axis 0:")
print(concatenated_array_0)

concatenated_array_1 = np.concatenate((array1, array2), axis=1)   # Concatenate along axis 1 (columns)
print("\nConcatenated array along axis 1:")
print(concatenated_array_1)


Concatenated array along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


# **Splitting**

In [3]:
import numpy as np

array = np.arange(16).reshape(4, 4)
print("Original array:")
print(array)

split_array_0 = np.split(array, 2, axis=0)    # Split into 2 sub-arrays along axis 0 (rows)
print("\nSplit arrays along axis 0:")
print(split_array_0)

split_array_1 = np.split(array, 2, axis=1)    # Split into 2 sub-arrays along axis 1 (columns)
print("\nSplit arrays along axis 1:")
print(split_array_1)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Split arrays along axis 0:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]

Split arrays along axis 1:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


# **Horizontal Split (hsplit)**

In [4]:
import numpy as np

array = np.arange(16).reshape(4, 4)
print("Original array:")
print(array)

hsplit_array = np.hsplit(array, 2)    # Horizontal split into 2 sub-arrays
print("\nHorizontally split arrays:")
print(hsplit_array)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Horizontally split arrays:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


# **Vertical Split (vsplit)**

In [5]:
import numpy as np

array = np.arange(16).reshape(4, 4)
print("Original array:")
print(array)

vsplit_array = np.vsplit(array, 2)      # Vertical split into 2 sub-arrays
print("\nVertically split arrays:")
print(vsplit_array)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Vertically split arrays:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
